#!/bin/bash
#
# Perform necessary metasploit setup steps
# prior to installing package.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

BINS="msfbinscan msfconsole msfd msfelfscan msfmachscan msfpescan msfrop msfrpc msfrpcd msfupdate msfvenom"

if [ -x /usr/sbin/update-alternatives ] ; then
	for BIN in $BINS; do
		update-alternatives --remove $BIN /opt/metasploit-framework/bin/msfwrapper
	done
fi

exit 0
